# Generated by Django 4.2.13 on 2024-05-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('position', models.CharField(choices=[('manager', 'Manager'), ('engineer', 'Engineer'), ('sysadmin', 'System Administrator')], max_length=50)),
                ('department', models.CharField(choices=[('sales', 'Sales Department'), ('tech', 'Technical Department')], max_length=50)),
                ('hire_date', models.DateField()),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('terminated', 'Terminated')], max_length=50)),
                ('projects', models.TextField(blank=True)),
            ],
        ),
    ]
