# Generated by Django 4.2.13 on 2024-06-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Отдел продаж', 'Отдел продаж'), ('Тех. отдел', 'Технический отдел'), ('Отдел кадров', 'Отдел кадров'), ('Экн. отдел', 'Финансово-экономический отдел'), ('Отдел безопасности', 'Отдел безопасности'), ('Складской отдел', 'Складской отдел'), ('Отдел приёма товара', 'Отдел приёма товара')], max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(verbose_name='Дата приема на работу'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='Мобильный телефон'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Продавец-кассир', 'Продавец-кассир'), ('Приёмщик товара', 'Приёмщик товара'), ('Комплектовщик', 'Комплектовщик'), ('Сборщик', 'Сборщик заказов'), ('Дир. магазина', 'Директор магазина'), ('Зам. директора', 'Заместитель директора'), ('Кладовщик', 'Кладовщик'), ('Охранник', 'Сотрудники службы безопасности'), ('Уборщик', 'Уборщик '), ('Сис. админ', 'Системный администратор'), ('Менеджер', 'Менеджер по персоналу '), ('Бухгалтер', 'Бухгалтер')], max_length=100, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='projects',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Работает', 'Работает'), ('Уволен', 'Уволен')], max_length=10, verbose_name='Статус'),
        ),
    ]
